name: workflow

on:
    push:
        branches:
            - main
        
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Code
          uses: actions/checkout@v3

        - name: Set up Python 3.10
          uses: actions/setup-python@v3
          with:
            python-version: 3.10
        - name: Install Dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
        
        - name: Lint code
          run: echo "Linting repository"

        - name: Run unit tests
          run: echo "Running unit tests"
    
    sonarqube:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - name: SonarQube Scan
          uses: sonarsource/sonarqube-scan-action@master
          env:
            SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
            SONAR_HOST_URL: ${{secrets.SONAR_HOST_URL}}